- core/README.md
- core/src/main/java/io/knotx/fragments/handler/action/PayloadToBodyActionFactory.java
- core/src/test/java/io/knotx/fragments/handler/action/CircuitBreakerActionTest.java
- core/src/test/java/io/knotx/fragments/handler/action/PayloadToBodyActionFactoryTest.java
Payload to body action implementation
---
> Payload to body action implementation

- core/src/main/java/io/knotx/fragments/handler/FragmentsHandler.java
Adjust to removing fragments from RequestEvent
See https://github.com/Knotx/knotx-server-http/pull/27
---
> Adjust to removing fragments from RequestEvent

- api/build.gradle.kts
- core/build.gradle.kts
- engine/build.gradle.kts
> Not signed local maven publication

- assembler/README.md
- assembler/build.gradle.kts
- assembler/src/main/java/io/knotx/assembler/AssemblerRoutingHandlerFactory.java
- assembler/src/main/java/io/knotx/assembler/FragmentAssemblerHandler.java
- assembler/src/main/java/io/knotx/assembler/package-info.java
- assembler/src/main/resources/META-INF/services/io.knotx.server.api.handler.RoutingHandlerFactory
- assembler/src/test/java/io/knotx/assembler/FragmentAssemblerHandlerTest.java
- gradle/codegen.deps.gradle.kts
- settings.gradle.kts
Move assembler to fragments repo
This is the final structural change on the repository.
---
> Move assembler to fragments repo

- README.md
- assembler/README.md
- gradle.properties
- handler/api/README.md
- handler/core/README.md
- handler/engine/README.md
- settings.gradle.kts
- supplier/README.md
- supplier/html-splitter/README.md
Fix docs URLs and prepare to rename the repo to `knotx-fragments`.
---
> Prepare to rename the repo

- handler/core/src/main/java/io/knotx/fragments/handler/action/ActionProvider.java
- settings.gradle.kts
- supplier/html-splitter/README.md
- supplier/single-fragment/README.md
- supplier/single-fragment/build.gradle.kts
- supplier/single-fragment/docs/asciidoc/dataobjects.adoc
- supplier/single-fragment/gradle.properties
- supplier/single-fragment/src/main/java/io/knotx/fragments/supplier/single/SingleFragmentSupplier.java
- supplier/single-fragment/src/main/java/io/knotx/fragments/supplier/single/SingleFragmentSupplierOptions.java
- supplier/single-fragment/src/main/java/io/knotx/fragments/supplier/single/SingleFragmentSupplierRoutingHandlerFactory.java
- supplier/single-fragment/src/main/java/io/knotx/fragments/supplier/single/package-info.java
- supplier/single-fragment/src/main/resources/META-INF/services/io.knotx.server.api.handler.RoutingHandlerFactory
- supplier/single-fragment/src/test/java/io/knotx/fragments/supplier/single/SingleFragmentSupplierTest.java
Fragments supplier that adds a single Fragment to the context.
See #34 
---
> Single fragment supplier

- handler/core/build.gradle.kts
- handler/core/src/main/java/io/knotx/fragments/handler/action/InMemoryCacheActionFactory.java
- handler/core/src/main/java/io/knotx/fragments/handler/action/PayloadToBodyActionFactory.java
> Enable reading parameters from payload in HTTP action

- handler/core/src/main/java/io/knotx/fragments/handler/action/InMemoryCacheActionFactory.java
> add placeholder source defintion

- assembler/src/main/java/io/knotx/fragments/assembler/FragmentsAssemblerHandler.java
- assembler/src/main/java/io/knotx/fragments/assembler/FragmentsAssemblerHandlerFactory.java
- assembler/src/main/resources/META-INF/services/io.knotx.server.api.handler.RoutingHandlerFactory
- assembler/src/test/java/io/knotx/fragments/assembler/FragmentsAssemblerHandlerTest.java
- supplier/html-splitter/README.md
- supplier/html-splitter/src/main/java/io/knotx/fragments/supplier/html/splitter/HtmlFragmentsSupplier.java
- supplier/html-splitter/src/main/java/io/knotx/fragments/supplier/html/splitter/HtmlFragmentsSupplierFactory.java
- supplier/html-splitter/src/main/resources/META-INF/services/io.knotx.server.api.handler.RoutingHandlerFactory
- supplier/html-splitter/src/test/java/io/knotx/fragments/supplier/html/splitter/HtmlFragmentsSupplierTest.java
- supplier/single-fragment/src/main/java/io/knotx/fragments/supplier/single/SingleFragmentSupplierFactory.java
- supplier/single-fragment/src/main/resources/META-INF/services/io.knotx.server.api.handler.RoutingHandlerFactory
> Rename spliter and assembler

- README.md
> Readme update: purpose and description

- azure-pipelines.yml
- handler/core/src/main/java/io/knotx/fragments/handler/FragmentsHandler.java
- handler/core/src/main/java/io/knotx/fragments/handler/action/ActionOptions.java
- handler/core/src/test/java/io/knotx/fragments/handler/action/ActionProviderTest.java
Fixing an issue #63 .
Unit tests added.
---
> Fixing NPE, added Azure docker build

- handler/api/src/main/java/io/knotx/fragments/handler/api/actionlog/ActionLogBuilder.java
- handler/api/src/main/java/io/knotx/fragments/handler/api/actionlog/ActionLogLevel.java
- handler/api/src/main/java/io/knotx/fragments/handler/api/actionlog/ActionLogger.java
- handler/core/src/test/java/io/knotx/fragments/handler/action/cb/CircuitBreakerDoActions.java
- handler/core/src/test/java/io/knotx/fragments/handler/action/logging/InlineBodyActionFactoryLoggingTest.java
#85 HTTP Action log implementation.
Added ability to log JsonArray objects in ActionLogger and ActionLogBuilder
Previously we were unable to log JsonArray objects, only JsonObject and String were supported
---
> Feature/http action logs (#71)

- handler/actions/docs/asciidoc/dataobjects.adoc
- handler/core/src/main/java/io/knotx/fragments/task/factory/node/action/ActionNodeFactory.java
- handler/core/src/main/java/io/knotx/fragments/task/factory/node/subtasks/SubtasksNodeFactory.java
- handler/engine/build.gradle.kts
- handler/engine/src/main/java/io/knotx/fragments/engine/TaskEngine.java
- handler/engine/src/main/java/io/knotx/fragments/engine/graph/CompositeNode.java
- handler/engine/src/test/java/io/knotx/fragments/engine/FragmentsEngineConcurrencyTest.java
- handler/engine/src/test/java/io/knotx/fragments/engine/FragmentsEngineOrderTest.java
- handler/engine/src/test/java/io/knotx/fragments/engine/Nodes.java
- handler/engine/src/test/java/io/knotx/fragments/engine/TaskEngineCompositeNodeTest.java
- handler/engine/src/test/java/io/knotx/fragments/engine/TaskEngineScenariosTest.java
- handler/engine/src/test/java/io/knotx/fragments/engine/TaskEngineSingleOperationTest.java
- handler/engine/src/test/java/io/knotx/fragments/engine/TestFunction.java
- handler/engine/src/test/java/io/knotx/fragments/engine/Transitions.java
Extract `single` and `composite` node interfaces.
---
> #93 Extract interfaces for single and composite nodes

- handler/actions/src/main/java/io/knotx/fragments/handler/action/InMemoryCacheActionFactory.java
- handler/actions/src/test/java/io/knotx/fragments/handler/action/InMemoryCacheActionFactoryTest.java
- handler/actions/src/test/java/io/knotx/fragments/handler/action/logging/InMemoryCacheActionFactoryLoggingTest.java
Instead of passing failure from doAction in InMemoryCacheAction we're passing `ERROR_TRANSITION` in order to preserve action logs
---
> #89 error transition instead of failure

- handler/actions/docs/asciidoc/dataobjects.adoc
- handler/actions/src/main/java/io/knotx/fragments/handler/action/http/options/HttpActionOptions.java
> #125 Fix HttpActionOptions converter by making setters public.

- handler/README.md
- handler/core/docs/asciidoc/dataobjects.adoc
- handler/core/src/main/java/io/knotx/fragments/handler/FragmentsHandler.java
- handler/core/src/main/java/io/knotx/fragments/handler/FragmentsHandlerOptions.java
- handler/core/src/test/java/io/knotx/fragments/handler/FragmentsHandlerTest.java
- handler/core/src/test/resources/handler/taskFactoryWithInvalidFragmentsAllowed.conf
>  #145 Implement flag to force fragments handler to succeed

- build.gradle.kts
- settings.gradle.kts
Add support for running tests for each composite-build modules tests. Apply plugin `composite-build-support` (renamed `publish-all-composite`).
https://github.com/Knotx/knotx-stack/issues/57
---
> Execute tests from all included knotx-stack builds

- CHANGELOG.md
- action/core/src/main/java/io/knotx/fragments/action/core/ActionProvider.java
- action/core/src/test/java/io/knotx/fragments/action/core/ActionProviderTest.java
- task/factory/default/src/main/java/io/knotx/fragments/task/factory/generic/node/action/ActionNodeFactory.java
Changes `Supplier<Iterator<ActionFactory>>` constructor argument type to `Supplier<Iterable<ActionFactory>>` as it simplifies usage.
Closes #189
---
> #189 Improve ActionProvider's constructor

- action/library/README.md
HTTP Action documentation update.
---
> HTTP Action docs update

- action/api/src/main/java/io/knotx/fragments/action/api/invoker/ActionInvoker.java
Publication plugin failed on javadocs check.
Errors:
```
error: attribute not supported in HTML5: cellspacing
error: attribute not supported in HTML5: summary
```
---
> Fix doclint check for ActionInvoker

- CHANGELOG.md
- action/library/build.gradle.kts
- action/library/src/test/java/io/knotx/fragments/action/library/CopyPayloadKeyActionFactoryTest.java
- action/library/src/test/java/io/knotx/fragments/action/library/cb/CircuitBreakerResponderTest.java
- action/library/src/test/java/io/knotx/fragments/action/library/http/EndpointInvokerIntegrationTest.java
- action/library/src/test/java/io/knotx/fragments/action/library/logging/InMemoryCacheActionFactoryLoggingTest.java
- task/functional/build.gradle.kts
- task/handler/core/build.gradle.kts
Fixes #219.
Includes:
- https://github.com/Knotx/knotx-junit5/pull/76
- https://github.com/Knotx/knotx-repository-connector/pull/39
- https://github.com/Knotx/knotx-stack/pull/138
---
> #219 update wiremock dependency
